name: ceshi3

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: go version
        run: | 
          go version
