name: ceshi1

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push ${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [ red, blue ]
        b: [ apple, orange ]
      max-parallel: 5
    outputs:
      digests: ${{ steps.test.outputs.output }}
    steps:
      - name: test
        shell: bash
        id: test
        run: |
          echo "output=${{ matrix.a }}-${{ matrix.b }}" >> ${GITHUB_OUTPUT}

  attest:
    name: Generate artifact attestation
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: tell me how output works
        shell: cat {0}
        run: |
          ${{ toJson(needs) }}

      # - name: Generate artifact attestation for main image
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ${{ matrix.image }}
      #     subject-digest: ${{ matrix.digest_main }}
      #     push-to-registry: ${{ matrix.image }}
      #     push-to-registry-token: ${{ steps.push.outputs.id-token }}
